
_format_version: "1.1"

plugins:
- name: prometheus

services:
- name: coins
  url: https://api.coindesk.com/v1/bpi/currentprice.json
  routes:
  - name: coins
    paths:
    - /coins

- name: money
  url: https://economia.awesomeapi.com.br/json/all
  routes:
  - name: money
    paths:
    - /money